"""add interpretations table and interpreted status

Revision ID: 2520310c3acf
Revises: f5f0af118106
Create Date: 2026-09-17 23:19:48.734691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2520310c3acf'
down_revision: Union[str, Sequence[str], None] = 'f5f0af118106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpretations',
    sa.Column('reading_id', sa.Uuid(), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('reference_data_version', sa.String(length=64), nullable=False),
    sa.Column('interpretive_model', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interpretations')
    # ### end Alembic commands ###
