"""add scripture references table

Revision ID: 31bea9b1c3f1
Revises: 5dc3cb471b18
Create Date: 2026-09-20 16:08:32.939958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bea9b1c3f1'
down_revision: Union[str, Sequence[str], None] = '5dc3cb471b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripture_references',
    sa.Column('theme', sa.String(length=60), nullable=False),
    sa.Column('book', sa.String(length=30), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse_start', sa.Integer(), nullable=False),
    sa.Column('verse_end', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(length=60), nullable=False),
    sa.Column('translation', sa.String(length=10), nullable=False),
    sa.Column('context_note', sa.Text(), nullable=False),
    sa.Column('reflection_connection', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('chapter >= 1', name='ck_scripture_references_chapter_positive'),
    sa.CheckConstraint('verse_end IS NULL OR verse_end >= verse_start', name='ck_scripture_references_verse_end_after_start'),
    sa.CheckConstraint('verse_start >= 1', name='ck_scripture_references_verse_start_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme', 'book', 'chapter', 'verse_start', 'translation', name='uq_scripture_references_theme_book_chapter_verse_translation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripture_references')
    # ### end Alembic commands ###
