"""create data foundation tables

Revision ID: 3468c874958d
Revises: 
Create Date: 2026-09-17 20:49:57.312008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3468c874958d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_decks_name')
    )
    op.create_table('reflection_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spreads',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_duplicate_cards', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_spreads_name')
    )
    op.create_table('cards',
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('arcana', sa.Enum('major', 'minor', name='arcana', native_enum=False, length=20), nullable=False),
    sa.Column('suit', sa.Enum('wands', 'cups', 'swords', 'pentacles', name='suit', native_enum=False, length=20), nullable=True),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.Column('image_ref', sa.String(length=255), nullable=True),
    sa.Column('base_meaning_upright', sa.Text(), nullable=True),
    sa.Column('base_meaning_reversed', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('primary_themes', sa.JSON(), nullable=False),
    sa.Column('secondary_themes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(arcana = 'major' AND suit IS NULL) OR (arcana = 'minor' AND suit IS NOT NULL)", name='ck_cards_suit_matches_arcana'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'name', name='uq_cards_deck_id_name')
    )
    op.create_table('readings',
    sa.Column('reflection_session_id', sa.Uuid(), nullable=False),
    sa.Column('spread_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_domain', sa.String(length=60), nullable=True),
    sa.Column('draw_method', sa.Enum('physical', 'digital', name='draw_method', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('drafting', 'spread_complete', 'saved', name='reading_status', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reflection_session_id'], ['reflection_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spread_id'], ['spreads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reflection_session_id')
    )
    op.create_table('spread_positions',
    sa.Column('spread_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position_order', sa.Integer(), nullable=False),
    sa.Column('semantic_role', sa.Enum('significator', 'situation', 'recent_past', 'influence_blocker', 'near_future', 'advice', 'advice_clarifier', 'general', name='semantic_role', native_enum=False, length=30), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('position_order >= 1', name='ck_spread_positions_position_order_positive'),
    sa.ForeignKeyConstraint(['spread_id'], ['spreads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spread_id', 'position_order', name='uq_spread_positions_spread_id_position_order')
    )
    op.create_table('card_draws',
    sa.Column('reading_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('orientation', sa.Enum('upright', 'reversed', name='orientation', native_enum=False, length=20), nullable=False),
    sa.Column('draw_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('draw_order >= 1', name='ck_card_draws_draw_order_positive'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['spread_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reading_id', 'draw_order', name='uq_card_draws_reading_id_draw_order'),
    sa.UniqueConstraint('reading_id', 'position_id', name='uq_card_draws_reading_id_position_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_draws')
    op.drop_table('spread_positions')
    op.drop_table('readings')
    op.drop_table('cards')
    op.drop_table('spreads')
    op.drop_table('reflection_sessions')
    op.drop_table('decks')
    # ### end Alembic commands ###
