"""add card correspondences table

Revision ID: f5f0af118106
Revises: 3468c874958d
Create Date: 2026-09-17 21:27:11.795513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f0af118106'
down_revision: Union[str, Sequence[str], None] = '3468c874958d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_correspondences',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('tradition_name', sa.String(length=120), nullable=True),
    sa.Column('element', sa.String(length=20), nullable=False),
    sa.Column('zodiac_signs', sa.JSON(), nullable=False),
    sa.Column('zodiac_symbols', sa.JSON(), nullable=False),
    sa.Column('astrological_influence', sa.String(length=255), nullable=False),
    sa.Column('elemental_gender', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('animal', sa.String(length=255), nullable=True),
    sa.Column('stone', sa.String(length=255), nullable=True),
    sa.Column('astrology_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_correspondences')
    # ### end Alembic commands ###
